AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  AzaoFunc:
    Type: AWS::Serverless::Function
    Properties:
      Handler: pipeline_lambda.lambda_handler
      Runtime: python3.12
      CodeUri: .
      MemorySize: 1024
      Timeout: 30
